# docker-compose.yml
version: '3.8'

services:
  vue-app:
    build:
      context: . # Current directory
      dockerfile: Dockerfile
    ports:
      - '8080:80' # Map port 80 in the container to port 8080 on the host
    volumes:
      - .:/app # Optional: Mount the current directory to allow for live updates (not recommended for production)
